[env:esp32s3dev]
platform = espressif32 @ 6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    esp32-camera
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit PWM Servo Driver Library
    links2004/WebSockets @ ^2.4.1

upload_flags =
    --no-stub
    --before=default_reset
    --after=hard_reset

monitor_dtr = 0
monitor_rts = 0
