// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCBR9gx3c4PqlqNn-AgbKifsUx3_dsIg',
    appId: '1:719697570239:web:226a5b993b906ee6d9190a',
    messagingSenderId: '719697570239',
    projectId: 'ares-01-i2p',
    authDomain: 'ares-01-i2p.firebaseapp.com',
    databaseURL: 'https://ares-01-i2p-default-rtdb.firebaseio.com',
    storageBucket: 'ares-01-i2p.firebasestorage.app',
    measurementId: 'G-8H7M0PFZQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0dqHKv133xji8b1Db72HyD0yp2Y4xng',
    appId: '1:719697570239:android:de86e8d08e8932c3d9190a',
    messagingSenderId: '719697570239',
    projectId: 'ares-01-i2p',
    databaseURL: 'https://ares-01-i2p-default-rtdb.firebaseio.com',
    storageBucket: 'ares-01-i2p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHzsglBsf9pfiwrtGqCBiRgEOGetFivag',
    appId: '1:719697570239:ios:0d34f9655958f93fd9190a',
    messagingSenderId: '719697570239',
    projectId: 'ares-01-i2p',
    databaseURL: 'https://ares-01-i2p-default-rtdb.firebaseio.com',
    storageBucket: 'ares-01-i2p.firebasestorage.app',
    iosBundleId: 'com.example.roverControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHzsglBsf9pfiwrtGqCBiRgEOGetFivag',
    appId: '1:719697570239:ios:0d34f9655958f93fd9190a',
    messagingSenderId: '719697570239',
    projectId: 'ares-01-i2p',
    databaseURL: 'https://ares-01-i2p-default-rtdb.firebaseio.com',
    storageBucket: 'ares-01-i2p.firebasestorage.app',
    iosBundleId: 'com.example.roverControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwCBR9gx3c4PqlqNn-AgbKifsUx3_dsIg',
    appId: '1:719697570239:web:2317be6e4c08e7dad9190a',
    messagingSenderId: '719697570239',
    projectId: 'ares-01-i2p',
    authDomain: 'ares-01-i2p.firebaseapp.com',
    databaseURL: 'https://ares-01-i2p-default-rtdb.firebaseio.com',
    storageBucket: 'ares-01-i2p.firebasestorage.app',
    measurementId: 'G-X3L7DP5K7Y',
  );
}
